spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.136.105.24:3306/filingassistance?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: pje1234

server:
  port: 8090

mybatis:
  type-aliases-package: cn.edu.guet.filingassistance_springboot.bean
  mapper-locations: classpath:mapper/*Mapper.xml